spring:
  profiles:
    active:
    - docker

#server:
#  port: 8080
#
#spring:
#  datasource:
#    url: jdbc:postgresql://database-station-2.cbaqou6cmbcu.ap-south-1.rds.amazonaws.com/capstone
#    username: postgres
#    password: postgres
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#
#jwt:
#  secret: 0194cc426c227da58721b57cdde3fc8b6se4cr67et1k56ey9
